// =================================================================
// Jenkinsfile  —  generated by DevOps Pipeline Platform
// App: java-calculator  |  Type: java
// =================================================================
pipeline {
  agent { label 'linux' }

  options {
    buildDiscarder(logRotator(numToKeepStr: '20'))
    timeout(time: 60, unit: 'MINUTES')
  }

  environment {
    APP_NAME    = 'java-calculator'
    APP_VERSION = '1.0.0'
    SONAR_TOKEN = credentials('sonar-token')
    CHECKMARX_TOKEN = credentials('checkmarx-token')
  }

  // push / pull_request: configure an SCM webhook on the repo to trigger builds,
  // or add  triggers { pollSCM('H/5 * * * *') }  to poll for changes instead.

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/ankitbharti1998/java-calculator.git'
      }
    }
    stage('Build') {
      steps {
        sh 'sh onboarding/ci/build/default-build.sh {WORKFLOW_CONTEXT}'
      }
    }
    stage('Test') {
      steps {
        // Coverage gate: 80% (enforced inside the test script)
        sh 'sh onboarding/ci/test/default-test.sh {WORKFLOW_CONTEXT}'
      }
    }
    stage('SonarQube Analysis') {
      steps {
        sh 'sh onboarding/ci/sonar/default-sonar.sh'
      }
    }
    stage('Checkmarx SAST') {
      steps {
        sh 'sh onboarding/ci/checkmarx/default-checkmarx.sh'
      }
    }
    stage('Architecture-as-Code') {
      steps {
        sh 'sh onboarding/ci/arch/default-arch.sh'
      }
    }
  }

  post {
    always {
      echo "Pipeline finished with status: ${currentBuild.currentResult}"
    }
  }
}
